<a href="https://colab.research.google.com/github/atanu22-iitk/DLCV/blob/main/Assignment_dlcv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
from traitlets.config.loader import JSONFileConfigLoader
from numpy.core.getlimits import array

import numpy as np
import matplotlib.pyplot as plt



def read_data(file):
  import pickle
  data=open(file, 'rb')
  dict = pickle.load(data, encoding='bytes')
  return dict

def image_array(image_data):
    global R_ch,G_ch,B_ch
    R_ch=np.array([image_data[b'data'][1,:32]])
    G_ch=np.array([image_data[b'data'][1,1024:1056]])
    B_ch=np.array([image_data[b'data'][1,2048:2080]])

    for i in range(32,1024,32):
        data_R=np.array(image_data[b'data'][1,i:i+32])
        R_ch=np.append(R_ch, [data_R], axis=0)
        i+=32

    for i in range(1056,2048,32):
        data_G=np.array(image_data[b'data'][1,i:i+32])
        G_ch=np.append(G_ch, [data_G], axis=0)
        i+=32

    for i in range(2080,3072,32):
        data_B=np.array(image_data[b'data'][1,i:i+32])
        B_ch=np.append(B_ch, [data_B], axis=0)
        i+=32

    print('Red:',R_ch)
    print('Green:',G_ch)
    print('Blue:',B_ch)
    print(type(R_ch))
    
    print(R_ch.shape)
    print(G_ch.shape)
    print(B_ch.shape)
    
    
    image_3d=np.zeros((32,32),dtype=np.uint8)
    for i in range(0,32,1):
      image_2d=np.array((R_ch[0,0],G_ch[0,0],B_ch[0,0]), dtype=np.uint8)
      for j in range(1,32,1):
        image=np.array([R_ch[i][j],G_ch[i][j],B_ch[i][j]])
        # print(image)
        
        image_2d= np.append(image_2d, image, axis=None)
        print(image_2d[1])
      image_2=image_2d.reshape(32,32,-1)
     # image_3d=np.append(image_3d, image_2d, axis=0)

    # print(image_3d)
    #print(image_3d.shape)
    #plt.imshow(image_3d)
    plt.show()

    plt.imshow(R_ch)
    plt.show()
    plt.imshow(G_ch)
    plt.show()
    plt.imshow(B_ch)
    plt.show()

    return R_ch

def min_max(arr):
  min=np.min(arr)
  max=np.max(arr)
  return min, max

def main():
    file='/content/drive/MyDrive/Colab Notebooks/cifar-10-batches-py/data_batch_1'
    image_data=read_data(file)
    print('Showing Data:')
    cnt=0
    for item in image_data:
      print('File contain',cnt,' is:', item)
      cnt +=1
    image = np.array(image_array(image_data))
    
    print(image.shape)
    print(image)

    R_min_max=min_max(R_ch)
    G_min_max=min_max(G_ch)
    B_min_max=min_max(B_ch)
    print('Rmin:',R_min_max[0])
    print('Rmax:',R_min_max[1])
    print('Gmin:',G_min_max[0])
    print('Gmax:',G_min_max[1])
    print('Bmin:',B_min_max[0])
    print('Bmax:',B_min_max[1])
# driver code
if __name__ == "__main__":
    
  # function call
  main()






Showing Data:
File contain 0  is: b'batch_label'
File contain 1  is: b'labels'
File contain 2  is: b'data'
File contain 3  is: b'filenames'
Red: [[154 126 105 ...  91  87  79]
 [140 145 125 ...  96  77  71]
 [140 139 115 ...  79  68  67]
 ...
 [175 156 154 ...  42  61  93]
 [165 156 159 ... 103 123 131]
 [163 158 163 ... 143 143 143]]
Green: [[177 137 104 ...  95  90  81]
 [160 153 125 ...  99  80  73]
 [155 146 115 ...  82  70  69]
 ...
 [167 154 160 ...  34  53  83]
 [154 152 161 ...  93 114 121]
 [148 148 156 ... 133 134 133]]
Blue: [[187 136  95 ...  71  71  70]
 [169 154 118 ...  78  62  61]
 [164 149 112 ...  64  55  55]
 ...
 [166 160 170 ...  36  57  91]
 [128 130 142 ...  96 120 131]
 [120 122 133 ... 139 142 144]]
<class 'numpy.ndarray'>
(32, 32)
(32, 32)
(32, 32)
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177


ValueError: ignored